language: generic
env: SWIFT_VERSION=4.2.1

matrix:
  include:
    - os: linux
      sudo: required
      dist: xenial
    - os: osx
      osx_image: xcode10.1

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - make
  - make test
