language: generic
env: SWIFT_VERSION=5.0.1

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode10.2 # Mojave

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - make
  - make test
